### ISSUE TITLE
handle invalid or missing auth token

### ISSUE THREAD

**Issue by srt32** [srt32/prpluck#4]
```
Get https://api.github.com/repos/thoughtbot/repo_name/pulls: OAuthError: Refresh: Token expired; no Refresh Token
panic: invalid argument to Int31n

goroutine 16 [running]:
runtime.panic(0x264180, 0xc208036410)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
math/rand.(*Rand).Int31n(0xc208036290, 0xc200000000, 0x13925183fb13974c)
    /usr/local/go/src/pkg/math/rand/rand.go:78 +0x6f
math/rand.Int31n(0x1392518300000000, 0x24acff4c)
    /usr/local/go/src/pkg/math/rand/rand.go:190 +0x32
main.main()
    /Users/simon/Code/go/src/github.com/srt32/prpluck/pluck.go:33 +0x3aa

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
    /usr/local/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
    /usr/local/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445
```

**Comment by srt32** [comment]
Done in https://github.com/srt32/prpluck/commit/b5a18ef88fe19b7db7750be1790a23755e5eab3c
